const List<String> affirmations = [
  '🌱 You are capable of handling whatever today brings.',
  '✨ Progress, not perfection.',
  '🔥 You have survived every hard day so far.',
  '👟 Small steps still move you forward.',
  '😌 You are allowed to rest without guilt.',
  '💛 You are worthy of good things.',
  '🌅 Today is a new chance to try again.',
  '💪 Your effort matters, even when it feels invisible.',
  '🌊 You are more resilient than you give yourself credit for.',
  '🧩 It is okay to not have it all figured out yet.',
];

const List<String> waterReminderMessages = [
  '💧 Psst... your body is 60% water, top it off!',
  '🥤 Hydration check! Take a sip.',
  '🌊 Time for a water break, champ.',
  '🚰 Your future self says thanks for this glass of water.',
  '🐫 Don\'t be a camel, drink some water now.',
  '💦 Quick reminder: water > coffee right now.',
  '🧃 Sip sip, hooray! Water time.',
  '🫗 Pour yourself some water, you\'ve earned it.',
  '🌱 Stay fresh, stay hydrated.',
  '💙 Your body called. It wants water.',
  '🧊 Cool down with a refreshing sip.',
  '🐟 Be like a fish. Get some water in you.',
  '🌵 Don\'t turn into a cactus. Hydrate!',
  '💦 A little H₂O goes a long way.',
  '🚿 Hydration station! Grab some water.',
  '🥛 This is your sign to drink some water.',
  '🌊 Ride the hydration wave. Take a sip!',
  '💧 Water break! Your kidneys will appreciate it.',
  '🫧 Hydrate now, conquer the world later.',
  '🥤 Your water bottle misses you.',
  '💦 Sip happens. Drink some water.',
  '🌞 Stay cool. Stay hydrated.',
  '🧠 Your brain wants a water break too.',
  '🚰 Water.exe needs to be installed.',
  '💻 Hydration update available. Install now?',
  '🔋 Low on fluids? Recharge with some water.',
  '⚡ Hydration boost incoming. Take a sip!',
  '🎮 Hydration checkpoint reached. +10 HP.',
  '❤️ Give your body some liquid love.',
  '🏃 Keep yourself running smoothly. Hydrate!',
  '🌊 Just keep sipping, just keep sipping.',
  '🫗 Pour. Sip. Repeat.',
  '🥤 One sip closer to peak hydration.',
  '💧 Tiny sip, big win.',
  '🏆 Hydration achievement unlocked!',
  '📢 Attention! This is your scheduled water break.',
  '⏰ Ding ding! It\'s hydration o\'clock.',
  '🧊 Ice cold reminder: drink some water.',
  '🫡 Hydration duty calls.',
  '👀 Hey... when was your last sip?',
  '🤨 That water bottle isn\'t going to drink itself.',
  '🫵 Yes, you. Drink some water.',
  '😤 Enough scrolling. Hydrate.',
  '📱 Put me down for two seconds and grab some water.',
  '🧃 Hydration level looking suspicious. Take a sip.',
  '🚨 Hydration alert! Water required.',
  '⚠️ Warning: vibes may improve after drinking water.',
  '🔔 Friendly hydration notification has entered the chat.',
  '✨ Hydrate and carry on.',
  '🌈 Add a little H₂O to your day.',
  '🪫 Battery low? Water might help.',
  '🧑‍💻 Your code can wait 30 seconds. Hydrate.',
  '⌨️ Ctrl + Alt + Hydrate.',
  '🔄 Refresh yourself. Drink some water.',
  '📡 Receiving transmission... it says DRINK WATER.',
  '🤖 Human maintenance required: add water.',
  '🧪 Recommended system update: H₂O.',
  '🖥️ Error 404: Hydration not found.',
  '💾 Save your progress. Drink some water.',
  '📊 Hydration metrics are down. Let\'s fix that.',
  '🍶 Water break detected. Proceed immediately.',
  '👑 Hydrate, royalty.',
  '🐸 Ribbit reminder: drink some water.',
  '🐳 Channel your inner whale. Hydrate.',
  '🦦 Stay hydrated, little otter.',
  '🐧 Even penguins know water is important.',
  '🌴 Vacation vibes start with hydration.',
  '🌧️ Be the rain. Drink the rain. Actually, just drink water.',
  '🌎 Earth has a lot of water. You should have some too.',
  '🚀 Fuel up for the rest of your day.',
  '⭐ Hydration side quest available.',
  '🎯 Today\'s objective: drink more water.',
  '📈 Invest in yourself. One sip at a time.',
  '💪 Strong people drink water. Probably.',
  '😎 Cool people stay hydrated.',
  '🥳 Celebrate being alive with a glass of water.',
  '🕺 Hydrate like nobody\'s watching.',
  '🛑 Stop! Hydration checkpoint.',
  '▶️ Resume your day after one refreshing sip.',
  '💤 Feeling sluggish? Give water a shot.',
  '☁️ Head in the clouds? Water break.',
  '🌙 Night owl reminder: hydrate before you keep scrolling.',
  '☀️ Good morning! Start with some H₂O.',
  '🍽️ Food is great. Water would look good next to it.',
  '🧘 Hydrate your body, then continue your quest.',
  '🏖️ Pretend you\'re at the beach. Take a sip.',
  '🎵 Sip it real good.',
  '💧 Plot twist: you should drink water.',
  '🥤 Breaking news: you could use a sip.',
  '🫗 Your daily side quest: empty that water bottle.',
  '💦 Hydration streak check! Keep it going.',
  '🏅 Another sip, another victory.',
  '🌟 You\'re doing great. Now drink some water.',
];
